package com.example.ui.screens

object Loc {
    private val en = mapOf(
        "welcome" to "ProMarket",
        "tagline" to "AI Industrial Gateway",
        "hero_title" to "Futuristic Construction Tech 2026",
        "hero_subtitle" to "Billion-dollar modern startup equipment, industrial instruments, and building materials at enterprise scale.",
        "search_label" to "AI Search",
        "search_placeholder" to "Ask AI or search: drills, 220V, cements...",
        "ai_search_btn" to "AI Search",
        "ai_expl_tip" to "Enter custom needs (e.g. 'repairing concrete driveway under seismic stress') and tap 'AI Search' to let Gemini query products.",
        "categories" to "Industrial Categories",
        "featured" to "Featured Equipment",
        "about_item" to "Specs & Warranty",
        "details" to "Technical Specifications",
        "warranty" to "Warranty Period",
        "warehouse" to "Stock Hub",
        "price" to "Price",
        "add_to_cart" to "Add to Cart",
        "buy_now" to "Order Now",
        "reviews" to "Customer Testimonials",
        "faq_title" to "Frequently Asked Questions",
        "footer_rights" to "© 2026 ProMarket Enterprise. All rights reserved.",
        "cart_title" to "Secure Checkout Hub",
        "empty_cart" to "Your shopping cart is empty.",
        "customer_email" to "Customer Email",
        "delivery_addr" to "Delivery Destination Address",
        "select_region" to "Shipping Region",
        "express_del" to "Express Air Delivery (+$8.00)",
        "subtotal" to "Subtotal Items",
        "delivery_fee" to "Delivery Service Fee",
        "total" to "Total Amount",
        "pay_method" to "Payment Gateway",
        "pay_desc" to "Mock gateway sandbox is fully operational.",
        "place_order" to "Authorize Secure Electronic Payment",
        "orders_history" to "Historic Orders Log",
        "asst_welcome" to "ProMarket AI Copilot Terminal",
        "asst_tag" to "Ask about voltage ratios, structural anchors, or low-temp cement",
        "logs_terminal" to "Telegram Alert Node / System Audit Logs",
        "role_control" to "Enterprise Admin & Role Workspace",
        "change_role" to "Control Authority",
        "view_as" to "Portal View",
        "analytics_overview" to "Corporate Revenue Analytics",
        "stock_alert" to "Low Stock Alarm",
        "warehouse_title" to "Real-time Warehouse Monitoring",
        "delivery_tracker" to "Live Dispatch Map Coordinate Router",
        "broadcast_telegram" to "Broadcast Telegram Emergency Notification",
        "alert_low_stock" to "Low Stock Warning Alert triggered!",
        "stats_happy" to "Happy Contractors",
        "stats_delivered" to "Tons Delivered",
        "stats_uptime" to "System Uptime"
    )

    private val uz = mapOf(
        "welcome" to "ProMarket",
        "tagline" to "AI Sanoat Portali",
        "hero_title" to "Kelajak Qurilish Texnologiyasi 2026",
        "hero_subtitle" to "Milliard dollarlik eng zamonaviy sanoat drelari, og'ir yuk kranlari va yuqori sifatli qurilish ashyolari bir joyda.",
        "search_label" to "AI Qidiruv",
        "search_placeholder" to "AI orqali so'rang: drel, sement markasi, 220V...",
        "ai_search_btn" to "AI Tavsiya",
        "ai_expl_tip" to "Maxsus ehtiyojingizni yozing (masalan, 'seysmik faol joyda poydevor quyish uchun nimalar kerak?') va AI tugmasini bosing.",
        "categories" to "Sanoat Kategoriyalari",
        "featured" to "Tavsiya Etilgan Uskunalar",
        "about_item" to "Xususiyatlar va Kafolat",
        "details" to "Texnik Tafsilotlar",
        "warranty" to "Kafolat Muddati",
        "warehouse" to "Ombor Markazi",
        "price" to "Narxi",
        "add_to_cart" to "Savatga Qo'shish",
        "buy_now" to "Xarid Qilish",
        "reviews" to "Xaridorlar Fikr-Mulohazalari",
        "faq_title" to "Ko'p Beriladigan Savollar",
        "footer_rights" to "© 2026 ProMarket Enterprise. Barcha huquqlar himoyalangan.",
        "cart_title" to "Xavfsiz To'lov Bo'limi",
        "empty_cart" to "Sizning xarid savatingiz hozircha bo'sh.",
        "customer_email" to "Mijoz Elektron Pochtasi",
        "delivery_addr" to "Yetkazish Manzili",
        "select_region" to "Viloyat / Hudud",
        "express_del" to "Tezkor Havo Yetkazib Berish (+$8.00)",
        "subtotal" to "Mahsulotlar Jami",
        "delivery_fee" to "Kuryerlik Xizmati Narxi",
        "total" to "Umumiy Jami",
        "pay_method" to "To'lov Shlyuzi",
        "pay_desc" to "Demonstratsion to'lov tizimi quvvatli integratsiya qilingan.",
        "place_order" to "Elektron Xaridni Tasdiqlash",
        "orders_history" to "Buyurtmalar Tarixi",
        "asst_welcome" to "ProMarket AI Ko'makchi Terminali",
        "asst_tag" to "Kuchlanish darajalari, drel quvvati yoki sement sirlari haqida so'rang",
        "logs_terminal" to "Telegram Xabarnoma Tizimi / Tizim Audit Jurnali",
        "role_control" to "Korxonani Boshqarish va Rollar Paneli",
        "change_role" to "Boshqaruv Vakolati",
        "view_as" to "Portal Profili",
        "analytics_overview" to "Moliyaviy Daromad Grafigi",
        "stock_alert" to "Omborda Kam Qolgan Yuklar",
        "warehouse_title" to "Ombor Zaxiralarini Nazorat Qilish",
        "delivery_tracker" to "Yetkazish Koordinatalari Va Marshrut Xaritasi",
        "broadcast_telegram" to "Telegram Orqali Favqulodda Xabar Yuborish",
        "alert_low_stock" to "Ogohlantirish: Ombordagi zaxira juda kam qoldi!",
        "stats_happy" to "Mamnun Quruvchilar",
        "stats_delivered" to "Yetkazilgan Yuk (tonnada)",
        "stats_uptime" to "Tizim Barqarorligi"
    )

    private val ru = mapOf(
        "welcome" to "ProMarket",
        "tagline" to "AI Индустриальный Портал",
        "hero_title" to "Строительные Технологии Будущего 2026",
        "hero_subtitle" to "Промышленное оборудование, высокомощные инверторы, композитные материалы по стандартам стартапов на миллиард.",
        "search_label" to "AI Поиск",
        "search_placeholder" to "Поиск: дрели, сварочные аппараты, цемент...",
        "ai_search_btn" to "AI Помощь",
        "ai_expl_tip" to "Введите описание задачи (напр. 'заливка фундамента сейсмостойкого дома') и нажмите 'AI Помощь' для подбора инструментов через Gemini.",
        "categories" to "Индустриальные Категории",
        "featured" to "Рекомендуемое Оборудование",
        "about_item" to "Характеристики и Гарантия",
        "details" to "Техническая Спецификация",
        "warranty" to "Гарантийный Срок",
        "warehouse" to "Складской Узел",
        "price" to "Цена",
        "add_to_cart" to "В Корзину",
        "buy_now" to "Заказать Сейчас",
        "reviews" to "Отзывы Наших Клиентов",
        "faq_title" to "Часто Задаваемые Вопросы",
        "footer_rights" to "© 2026 ProMarket Enterprise. Все права защищены.",
        "cart_title" to "Защищенное Оформление",
        "empty_cart" to "Ваша корзина пуста.",
        "customer_email" to "Электронная Почта Клиента",
        "delivery_addr" to "Адрес Доставки Оборудования",
        "select_region" to "Регион Доставки",
        "express_del" to "Экспресс-Авиадоставка (+$8.00)",
        "subtotal" to "Стоимость Товаров",
        "delivery_fee" to "Тариф на Транспортировку",
        "total" to "Итоговая Сумма",
        "pay_method" to "Платежный Шлюз",
        "pay_desc" to "Тестовая подсистема полностью настроена.",
        "place_order" to "Авторизовать Электронную Оплату",
        "orders_history" to "Журнал Оформленных Заказов",
        "asst_welcome" to "Интеллектуальный Помощник ProMarket AI",
        "asst_tag" to "Задайте вопросы о вольтаже, мощности затяжки или прочности анкеров",
        "logs_terminal" to "Канал Уведомлений Telegram / Логи Системы",
        "role_control" to "Административная Панель Управления",
        "change_role" to "Уровень Доступа",
        "view_as" to "Профиль Портала",
        "analytics_overview" to "Финансовая Аналитика Выручки",
        "stock_alert" to "Оповещение о Низком Запасе",
        "warehouse_title" to "Мониторинг Складских Резервов",
        "delivery_tracker" to "Интерактивная Маршрутизация Логистики",
        "broadcast_telegram" to "Транслировать Срочное Оповещение в Telegram",
        "alert_low_stock" to "Внимание! Зафиксирован критически низкий уровень запасов!",
        "stats_happy" to "Довольных Подрядчиков",
        "stats_delivered" to "Доставлено Грузов (тонн)",
        "stats_uptime" to "Стабильность Сервера"
    )

    fun t(key: String, lang: String): String {
        return when (lang) {
            "uz" -> uz[key] ?: en[key] ?: key
            "ru" -> ru[key] ?: en[key] ?: key
            else -> en[key] ?: key
        }
    }
}
